### ISSUE TITLE
Support custom librdkafka configuration values

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [etf1/kafka-message-scheduler#25]
The code currently has a TODO "load config from a yaml file" when the Kafka consumer is initialized at: https://github.com/etf1/kafka-message-scheduler/blob/4c0c5220d47bd24c20ea92f9b1ee8e51150d6d6b/store/kafka/store.go#L42-L52

Currently both the producer and consumer configurations are hard-coded.  There are some additional configuration options we need to set in our environment for both producer and consumer, so it would be super helpful if we could have a mechanism to set any arbitrary [configuration options for librdkafka](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md).

The proposal to use a yaml file sounds like a good idea...

**Comment by fkarakas** [comment]
Yes Sir, i will take a look ASAP.
But to be clear the option `go.application.rebalance.enable": true` will be added each time, it is needed in order to be notified when partition assignments have changed and then to stop and remove schedules in the scheduler.
Regards,
