### ISSUE TITLE
Scheduling on millisecond instead of second ?

### ISSUE THREAD

**Issue by odinnou** [etf1/kafka-message-scheduler#39]
Hello, currently we need to set "scheduler-epoch" as seconds since 1970.

Do you have any plan to reduce the granilarity to milliseconds ?
Something like "scheduler-epoch-ms" as milliseconds since 1970.

It's not a common usecase right ? ^^

Thanks in advance
Kind regards

**Comment by fkarakas** [comment]
Hello @odinnou ,
To be honest, it is not a common use case. Second is enough in most of our needs.
In order to manage milliseconds, we need to make a little study, and see if it is doable easily.
